steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 
             'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}', '.']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 
             'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}' ]

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args: ['run', 'deploy', '${_SERVICE_NAME}',
       '--platform', 'managed', '--region', '${_REGION}',
       '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}']

    # force test
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args: ['run', 'services', 'update-traffic', '${_SERVICE_NAME}', '--to-latest',
       '--platform', 'managed', '--region', '${_REGION}']

substitutions:
    _SERVICE_NAME: solid-pancake
    _REGION: us-central1

