steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 
             'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}', '.']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 
             'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}' ]

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args: ['run', 'deploy', '${_SERVICE}',
       '--platform', 'managed', '--region', '${_REGION}',
       '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE}']

    # force test
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args: ['run', 'services', 'update-traffic', '${_SERVICE}', '--to-latest']

substitutions:
    _SERVICE_NAME: solid-pancake
    _REGION: us-central1
    _GITHUB_USER: glasnt

